### ISSUE TITLE
Sample Example output not what is expected

### ISSUE THREAD

**Issue by idkjs** [kitten/wonka#103]
```
let _= Wonka.interval(10)
  |> Wonka.sample(Wonka.interval(100))
  |> Wonka.take(2)
  |> Wonka.subscribe((. x) => print_int(x));
```
```
> node src/Sample.bs.js
## sample

`sample` emits the previously emitted value from an outer source every time
an inner source (notifier) emits.

In combination with `interval` it can be used to get values from a noisy source
more regularly.

/* Prints 10 20 to the console. */
715⏎  
```

Also, are there any tests for the reasonml code?

**Comment by kitten** [comment]
I'm not sure what the question here is, but not all examples are 100% accurate, but the code does what's described

**Comment by idkjs** [comment]
Sorry. The example expects an output of `10 20` but produces `7 15`. Since your code is probably right, the note should read `/* Prints 7 15 to the console. */`

Was just an FYI, sir.

**Comment by kitten** [comment]
I'll have to go through all the examples after I'm back at work and will update them ✌️

**Comment by idkjs** [comment]
Alread did here if that helps -> https://github.com/idkjs/wonka-docs

[PromiseSource](https://github.com/idkjs/wonka-docs/blob/main/src/sources/PromiseSource.re) doesnt work
[MakeSubject](https://github.com/idkjs/wonka-docs/blob/main/src/sources/MakeSubject.re) doesnt work
