### ISSUE TITLE
sourcing `./src/Wonka.bs.js`

### ISSUE THREAD

**Issue by idkjs** [kitten/wonka#110]
I ran wonka from a snowpack generated project and got this random error that `./src/Wonka.bs.js` could not be sourced.

![Screen Shot 2021-02-27 at 7 08 36 PM](https://user-images.githubusercontent.com/2370391/109395922-4a2fc300-792f-11eb-9772-60841226c95e.png)

Reproduction: https://github.com/idkjs/wonka-snowpack

Any idea what is going on here? 

Thank you, sir.

Having just seen #97, I am on node `v14.15.4`

```sh
> sw_vers
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64
> node -v
v14.15.4
>

```

**Comment by kitten** [comment]
It sounds like you have a Reason project on Snowpack and it's picking up the `exports` entry. Generally in Node this is enough to make that work: https://github.com/kitten/wonka/blob/2e89f5cc94dfb7edb2064465b8706cfe3dc382ef/package.json#L18

But it seems that that's not enough for Snowpack. I can add an additional entry for this root file, but I'd note that it's a bit weird for Snowpack not to support this "wildcard-like escape hatch"

**Comment by idkjs** [comment]
Thanks for the response. Mentioned it to @snowpack Seems like the #97 patch works which is fine. Not a serious project. Just an FYI.
