### ISSUE TITLE
Package not found: resolving package wonka in /

### ISSUE THREAD

**Issue by drejohnson** [kitten/wonka#2]
`Package not found: resolving package wonka in /`
I get this error when running `bsb -make-world`

**Comment by kitten** [comment]
Presumably you've added it to your list of dependencies in your `bsconfig.json`? Have you tried changing the name to `"Wonka"`? sometimes that curiously does it although the name is all-lowercase in this repo

**Comment by drejohnson** [comment]
Yep, I added to bsconfig.json. I've also tried `"Wonka"` also. Could it be a bs-platform version conflict? I'm running bs-platform v3.0.0.

```
Package not found: resolving package wonka in /
File "bsconfig.json", line 1
Error: package wonka not found or built , if it is not built
Please run 'bsb -make-world', otherwise please install it
```
My bsconfig.json

```
{
  "name": "reasonml-meiosis-callbags",
  "version": "0.1.0",
  "sources": {
    "dir": "src",
    "subdirs": true
  },
  "package-specs": {
    "module": "es6-global"
  },
  "suffix": ".bs.js",
  "bs-dependencies": ["wonka"],
  "warnings": {
    "error": "+101"
  },
  "namespace": true,
  "refmt": 3
}
```

**Comment by bsansouci** [comment]
Did you `npm install` wonka? If you do `ls node_modules` do you see a folder called `wonka`?

**Comment by drejohnson** [comment]
I installed with `yarn add wonka`. And yes, when I `ls node_modules` I see a `wonka` folder. Could it be a issue with yarn? Didn't think to try installing using `npm install`

**Comment by bsansouci** [comment]
Mmmh yarn reinstalls everything also... Do you still have `node_modules/bs-platform`?
Can you try running bsb locally? `./node_modules/.bin/bsb -make-world`

**Comment by drejohnson** [comment]
Yep, and running `bsb` locally works as expected.

**Comment by bsansouci** [comment]
Is this still an issue?

**Comment by mobily** [comment]
@bsansouci yup, I get this error too:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/1467712/44945141-e0c4ad00-ade2-11e8-9636-550c186771e2.png">

#9 fixes this issue
