### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by Daniel15** [kitten/wonka#21]
Are there any docs on this library? I see that it's used in urql and I'm trying to understand it but it's going way over my head 😛

**Comment by kitten** [comment]
It's actually very similar to RxJS but more synchronous, so a lot of their operators are the same for Wonka 😅 That being said, yes, docs are on the way, but I unfortunately haven't gotten to them yet 😢

**Comment by parkerziegler** [comment]
@kitten I should have some time this evening to work on some docs! I'll make a small PR to ensure we get the format right. Just starting off w/ basic API docs in Markdown and we can switch format / style as you see fit.

**Comment by Daniel15** [comment]
> It's actually very similar to RxJS but more synchronous, so a lot of their operators are the same for Wonka 😅

Cool, thanks. I looked through some RxJS docs and I think I have a bit of a better understanding of this programming model now. I've never used RxJS, I did use the original Rx (for C#) but that was many many years ago.
