### ISSUE TITLE
pairwise operator

### ISSUE THREAD

**Issue by sxd1140** [kitten/wonka#36]
Is have `pairwise` operator in wonka?

**Comment by kitten** [comment]
Hiya, for the sake of not having to cross-check this operator:

- what's `pairwise` and what does it do?
- what are you trying to achieve?

That may give me more information on what you're trying to get out of `wonka` 👍  Are you referring to it as an Rx operator? Would love to make sure that `wonka` supports every necessary use-case, but I'd love to keep the operators to a minimum, since I think it already has all the operators needed to fulfill lots of usecases

**Comment by sxd1140** [comment]
I need handle scroller change event, so need `current scroller position` and `last scroller position` to know scrolling direction.

**Comment by kitten** [comment]
Sounds like you were thinking of the [`combine` operator](https://wonka.kitten.sh/api/operators#combine), but if you have a single stream of position events you could also use the [`scan` operator](https://wonka.kitten.sh/api/operators#scan) to transform a single value into a stream of `{ last, current }` or sth similar

**Comment by sxd1140** [comment]
Thanks, I look `scan operator`.

`scan((acc, val) => acc + val)` in Example.
But in d.ts file https://github.com/kitten/wonka/blob/acc4e71e338ca178ad6da5748d7ffa6c3a3446c8/src/operators/wonka_operator_scan.d.ts#L3

What the second param I should pass?

**Comment by kitten** [comment]
Hm, seems like that example has a typo! As can be seen in the Reason example for it (and in the typings as you’ve already pointed out) there is a second argument indeed.

Like for `reduce` with `Array`s that second argument is for the initial value of the accumulation, but it’s not optional for `scan`

**Comment by sxd1140** [comment]
Ok. But seem like `scan` just pass one value.
```js
pipe(
   fromArray([1, 2, 3, 4, 5, 6]),
   scan((last, current) => current, 0),
    subscribe( [`I need two value here, last and current`] => {}),
);
```

**Comment by kitten** [comment]
You can just store the previous value using `scan` temporarily, then calculate your scroll trajectory separately:

```
  scan(
    ({ current: prev }, current) => ({ prev, current }),
    { current: null }
  ),
  map(({ prev, current }) => prev !== null ? current - prev : 0)
```

**Comment by sxd1140** [comment]
I got it.
Thanks a lot.
