### ISSUE TITLE
How to use combine?

### ISSUE THREAD

**Issue by sxd1140** [kitten/wonka#41]
Two arguments in example.

But

https://github.com/kitten/wonka/blob/f26cc6c1cbcbf4f3240a121575492c624f1e1980/src/operators/wonka_operator_combine.d.ts#L3

**Comment by kitten** [comment]
Hiya :wave: I think that's the example not matching the actual implementation. I'll get that fixed in a major bump, but the current usage is indeed `combine(sourceA)(sourceB)` or in a pipe: `pipe(sourceA, combine(sourceB))`

Sorry about that 😅
