### ISSUE TITLE
Combine N sources

### ISSUE THREAD

**Issue by EliaECoyote** [kitten/wonka#74]
I'm not sure about what's the best way to combine N sources with the **combine** operator.\
As described in the [docs](https://wonka.kitten.sh/api/operators#combine), the **combine** operator supports only 2 sources right now.\
Any idea on how to create a operator that combines a list/array of sources instead?

**Comment by kitten** [comment]
Right now you should repeat combine and map the result once you’ve combined all the sources you need.

Unfortunately combining “n” number of sources isn’t possible, because it wouldn’t be type-safe, so I didn’t think it valuable enough to be added

**Comment by EliaECoyote** [comment]
I wrote the following fns in order to combine sources **with the same type** as workaround for my use case

```reason
let combineArray = sourcesArray =>
  Belt.Array.reduce(sourcesArray, Wonka.fromValue([||]), (source, accSource) =>
    Wonka.combine(accSource, source)
    |> Wonka.map((. (result, resultsArray)) =>
         Array.append(resultsArray, [|result|])
       )
  );

let combineList = sourcesList =>
  sourcesList
  |> Array.of_list
  |> combineArray
  |> Wonka.map((. sourcesArray) => Array.to_list(sourcesArray));
```

the type of the `combineArray` fn is 
```reason
array(Wonka_types.sourceT('a)) => Wonka_types.sourceT(array('a))
```

I'll leave them here in case they're useful to someone
