### ISSUE TITLE
Runtime error when used with BuckleScript 8.1.0

### ISSUE THREAD

**Issue by gaku-sei** [kitten/wonka#85]
The new BS version seems to break, at runtime, the wonka take function:
<img width="970" alt="Capture d’écran 2020-06-23 à 11 55 23" src="https://user-images.githubusercontent.com/3982371/85355824-6da4a180-b548-11ea-8978-51639974a9e1.png">

The generated code for the take function looks something like this:

```js
if (state.taken < max) {
  if (signal) {
    state.taken = max;
    return state.talkback(/* Close */1); // Breaks here
  } else {
    return state.talkback(/* Pull */0);
  }
}
```

When logging, the `stage.talkback` propery is indeed `undefined` 😞

**Comment by BlueHotDog** [comment]
Tried looking at this, how this can even happen? isnt the whole point of Reasonml is to avoid such issues?

**Comment by kitten** [comment]
@gaku-sei that’s pretty interesting! I can take a look at the BS changes, but can you send the affected code snippet over please so I can get an initial idea of why the `talkback` isn’t set?

**Comment by Austaras** [comment]
@kitten the issue here is bs8 changed internal representation of variant from `tag`  to `TAG`, so dist need to be compiled with bs8 or it won't work
