### ISSUE TITLE
GPL license in opam/conf-m4

### ISSUE THREAD

**Issue by gmc77** [kitten/wonka#98]
Currently being flagged by fossa.com as a potential GPL issue

`esy.lock/opam/conf-m4.1`

Can anyone confirm that this is an actual issue or do we sidestep it because it's only used in the build process or similar?

Thanks.

**Comment by kitten** [comment]
See my comment here: https://github.com/gatsbyjs/gatsby/issues/27232#issuecomment-718812387

tl;dr it's not present in `wonka@4.0.15/esy.lock/`, the patch and also isn't a licence that is concerned with `wonka` itself, so your tool is misflagging this as it isn't scanning the right folders and files, i.e. `package.json:license` and `LICENSE` / `LICENSE.md`.

Hope that helps ✌️

**Comment by gmc77** [comment]
Perfect! Thanks for that ... gives me enough to flag it as a false positive.
